button:
  type: DigitalSensor
  port: 10
imu:
  type: IMU
rear_right_light_sensor:
  type: IRSensor
  port: 1
wait_for_light_sensor:
  type: AnalogSensor
  port: 2
front_right_light_sensor:
  type: IRSensor
  port: 4
front_left_light_sensor:
  type: IRSensor
  port: 5
front:
  type: SensorGroup
  left: front_left_light_sensor
  right: front_right_light_sensor
rear:
  type: SensorGroup
  right: rear_right_light_sensor
_motors: !include-merge motors.yml
_servos: !include-merge servos.yml