- M000SetupMission: setup
- M010GrabFirstPomsMission
- M020CollectSortedPomMission
- M030CollectLastPomsMission
- M040DriveToBasketsMission
- M050PullBasketsOutMission
- M060dropMachingPomsMission
- M070RetrunBasketsMission
- M999ShutdownMission: shutdown
- M080DriveAwayMission