- M000SetupMission: setup
- M999ShutdownMission: shutdown
- M007MoveToCenter
- M010FirstBrownCubeMission
- M020SecondBrownCubeMission
- M030GrabRedCubeMission
- M040DropFirstCubeStack
- M050DriveUpRampMission
- M070GrabUpperCube
- M080DriveToExternalLoadingDock
- M090PlaceSecondCubeMission
