front_left_motor:
  type: Motor
  port: 0
  inverted: false
  calibration:
    ticks_to_rad: 0.00409024
    vel_lpf_alpha: 0.05
    bemf_offset: 27.486
    static_friction_pct: 2
front_right_motor:
  type: Motor
  port: 1
  inverted: true
  calibration:
    ticks_to_rad: 0.00393925
    vel_lpf_alpha: 0.05
    bemf_offset: 34.9163
    static_friction_pct: 2
rear_left_motor:
  type: Motor
  port: 2
  inverted: false
  calibration:
    ticks_to_rad: 0.00367416
    vel_lpf_alpha: 0.05
    bemf_offset: 34.0453
    static_friction_pct: 10
rear_right_motor:
  type: Motor
  port: 3
  inverted: true
  calibration:
    ticks_to_rad: 0.0039164
    vel_lpf_alpha: 0.05
    bemf_offset: 45.087
    static_friction_pct: 2
