arm_base:
  type: Servo
  port: 0
  positions:
    _0deg: 110.3
    p90deg: 12.7
    max_left: 0
    m90deg: 201.8
    max_right: 208
arm_sholder:
  type: Servo
  port: 1
  positions:
    max_down: 195.3
    _0deg: 169.2
    p90deg: 69
    max_up: 0
arm_elbow:
  type: Servo
  port: 2
  positions:
    _0deg: 105.0
    p90deg: 195
    max_max: 208.0
    m90deg: 5.2
    max_minus: -25
arm_claw:
  type: Servo
  port: 3
  offset: 0
  positions:
    closed: 50
    p45deg: 97.8
    p90deg: 137.3