#!/bin/bash
: '
===========================================================
 Project:   ClawBot
 Generated: 2026-01-29 14:21:31
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
'

IP_ADDRESS="192.168.100.237"
USERNAME="pi"
rsync -avz --progress ./ $USERNAME@$IP_ADDRESS:/home/$USERNAME/programs/claw_bot