"""Auto-generated by Raccoon Toolchain (Tobias Madlberger / RaccoonOS Team)"""

from raccoon import (
    AnalogSensor,
    DigitalSensor,
    ETSensor,
    IRSensor,
    Motor,
    MotorCalibration,
    Servo,
    ServoPreset,
)
from raccoon import IMU as Imu


class Defs:
    imu = Imu()
    button = DigitalSensor(port=10)
    front_left_ir_sensor = IRSensor(port=1)
    front_right_ir_sensor = IRSensor(port=2)
    drum_light_sensor = IRSensor(port=0)
    wait_for_light_sensor = AnalogSensor(port=5)
    et_range_finder = ETSensor(port=3)
    IR_Distanz_to_pipe_sensor = ETSensor(port=4)
    front_left_motor = Motor(
        port=0,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.9527294517823562e-05, vel_lpf_alpha=1.0
        ),
    )
    front_right_motor = Motor(
        port=1,
        inverted=True,
        calibration=MotorCalibration(
            ticks_to_rad=1.556772726916546e-05, vel_lpf_alpha=1.0
        ),
    )
    drum_motor = Motor(
        port=2,
        inverted=False,
        calibration=MotorCalibration(ticks_to_rad=1.0, vel_lpf_alpha=1.0),
    )
    servo_help_motor = Motor(
        port=3,
        inverted=False,
        calibration=MotorCalibration(ticks_to_rad=1e-05, vel_lpf_alpha=1.0),
    )
    drum_pusher_servo = ServoPreset(
        Servo(port=0), positions={"close": 10, "open": 180, "block_angle": 55}
    )
    pom_remover_servo = ServoPreset(
        Servo(port=3),
        positions={
            "start": 95,
            "right": 20,
            "left": 180,
            "center": 100,
            "orange_pom_removel": 150,
        },
    )
    lift_drums_servo = ServoPreset(
        Servo(port=1),
        positions={
            "up": 170,
            "align_on_back": 70,
            "eject_position": 152,
            "seek_position": 162,
            "down": 5,
            "remove_D": 38,
            "remove_M": 70,
        },
    )
    analog_sensors = [
        front_left_ir_sensor,
        front_right_ir_sensor,
        drum_light_sensor,
        wait_for_light_sensor,
        et_range_finder,
        IR_Distanz_to_pipe_sensor,
    ]
    wait_for_light_mode = "auto"


defs = Defs()

__all__ = ["Defs", "defs"]
