"""
===========================================================
 Project:   tobi-test
 Generated: 2026-03-21 18:52:07
===========================================================

Authors:
  • Tobias Madlberger (Scaffold / CLI Author)
  • RaccoonOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
"""

from libstp import (
    AxisConstraints,
    AxisVelocityControlConfig,
    ChassisVelocityControlConfig,
    DifferentialKinematics,
    Drive,
    Feedforward,
    FusedOdometry,
    FusedOdometryConfig,
    GenericRobot,
    PidConfig,
    PidGains,
    SensorPosition,
    UnifiedMotionPidConfig,
    WheelPosition,
)

from src.hardware.defs import Defs


from src.missions.m00_setup_mission import M00SetupMission
from src.missions.m99_shutdown_mission import M99ShutdownMission
from src.missions.m02_collect_drums_mission import M02CollectDrumsMission


def _build_chassis_vel_config(vx=None, vy=None, wz=None):
    cfg = ChassisVelocityControlConfig()
    if vx is not None:
        cfg.vx = vx
    if vy is not None:
        cfg.vy = vy
    if wz is not None:
        cfg.wz = wz
    return cfg


class Robot(GenericRobot):
    defs = Defs()
    kinematics = DifferentialKinematics(
        left_motor=defs.front_left_motor,
        right_motor=defs.front_right_motor,
        wheel_radius=0.0345,
        wheelbase=0.16,
    )
    drive = Drive(
        kinematics=kinematics,
        vel_config=_build_chassis_vel_config(
            vx=AxisVelocityControlConfig(
                pid=PidGains(kp=0.0, ki=0.0, kd=0.0),
                ff=Feedforward(kS=0.0, kV=1.0, kA=0.0),
            ),
            vy=AxisVelocityControlConfig(
                pid=PidGains(kp=0.0, ki=0.0, kd=0.0),
                ff=Feedforward(kS=0.0, kV=1.0, kA=0.0),
            ),
            wz=AxisVelocityControlConfig(
                pid=PidGains(kp=0.0, ki=0.0, kd=0.0),
                ff=Feedforward(kS=0.0, kV=1.0, kA=0.0),
            ),
        ),
        imu=defs.imu,
    )
    odometry = FusedOdometry(
        imu=defs.imu, kinematics=kinematics, config=FusedOdometryConfig(bemf_trust=1.0)
    )
    motion_pid_config = UnifiedMotionPidConfig(
        distance=PidConfig(
            kp=3.0,
            ki=0.0,
            kd=0.0,
            integral_max=10.0,
            integral_deadband=0.01,
            derivative_lpf_alpha=0.5,
            output_min=-10.0,
            output_max=10.0,
        ),
        heading=PidConfig(
            kp=6,
            ki=0.0,
            kd=0.15,
            integral_max=10.0,
            integral_deadband=0.01,
            derivative_lpf_alpha=0.5,
            output_min=-10.0,
            output_max=10.0,
        ),
        velocity_ff=1.0,
        distance_tolerance_m=0.005,
        angle_tolerance_rad=0.017,
        saturation_derating_factor=0.85,
        saturation_min_scale=0.2,
        saturation_recovery_rate=0.02,
        saturation_hold_cycles=5,
        saturation_recovery_threshold=0.95,
        heading_saturation_derating_factor=0.85,
        heading_min_scale=0.25,
        heading_recovery_rate=0.05,
        heading_saturation_error_rad=0.01,
        heading_recovery_error_rad=0.005,
        linear=AxisConstraints(
            max_velocity=0.2368, acceleration=0.2798, deceleration=2.0532
        ),
        lateral=AxisConstraints(
            max_velocity=0.2145, acceleration=0.3922, deceleration=0.6504
        ),
        angular=AxisConstraints(max_velocity=2, acceleration=3, deceleration=3),
    )
    shutdown_in = 12000
    missions = [M02CollectDrumsMission()]
    setup_mission = M00SetupMission()
    shutdown_mission = M99ShutdownMission()
    width_cm = 13.0
    length_cm = 19.0
    rotation_center_forward_cm = -4.0
    rotation_center_strafe_cm = 0.0
    _sensor_positions = {
        defs.front_left_ir_sensor: SensorPosition(
            forward_cm=7.5, strafe_cm=7.25, clearance_cm=1.0
        ),
        defs.front_right_ir_sensor: SensorPosition(
            forward_cm=7.5, strafe_cm=-7.25, clearance_cm=1.0
        ),
        defs.drum_light_sensor: SensorPosition(
            forward_cm=7.5, strafe_cm=-7.25, clearance_cm=0
        ),
    }


__all__ = ["Robot"]
