"""
===========================================================
 Project:   tobi-test
 Generated: 2026-02-13 20:43:50
===========================================================

Authors:
  • Tobias Madlberger (Scaffold / CLI Author)
  • RaccoonOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
"""

from libstp import (
    AxisVelocityControlConfig,
    ChassisVelocityControlConfig,
    Drive,
    Feedforward,
    FusedOdometry,
    FusedOdometryConfig,
    GenericRobot,
    MecanumKinematics,
    MotionLimits,
    PidGains,
    SensorPosition,
    UnifiedMotionPidConfig,
    WheelPosition,
)

from src.hardware.defs import Defs


from src.missions.setup_mission import SetupMission
from src.missions.shutdown_mission import ShutdownMission
from src.missions.potato_mission import PotatoMission


def _build_chassis_vel_config(vx=None, vy=None, wz=None):
    cfg = ChassisVelocityControlConfig()
    if vx is not None:
        cfg.vx = vx
    if vy is not None:
        cfg.vy = vy
    if wz is not None:
        cfg.wz = wz
    return cfg


class Robot(GenericRobot):
    defs = Defs()
    kinematics = MecanumKinematics(
        back_left_motor=defs.rear_left_motor,
        back_right_motor=defs.rear_right_motor,
        front_left_motor=defs.front_left_motor,
        front_right_motor=defs.front_right_motor,
        max_acceleration=40.678,
        max_velocity=50.847,
        track_width=0.19,
        wheel_radius=0.0295,
        wheelbase=0.12,
    )
    drive = Drive(
        kinematics=kinematics,
        chassis_lim=MotionLimits(max_omega=999, max_v=999),
        vel_config=_build_chassis_vel_config(
            vx=AxisVelocityControlConfig(
                pid=PidGains(kp=0.1, ki=0.0, kd=0.0),
                ff=Feedforward(kS=0.0, kV=1.0, kA=0.0),
            ),
            vy=AxisVelocityControlConfig(
                pid=PidGains(kp=0.1, ki=0.0, kd=0.0),
                ff=Feedforward(kS=0.0, kV=1.0, kA=0.0),
            ),
            wz=AxisVelocityControlConfig(
                pid=PidGains(kp=0.65, ki=0.0, kd=0.0),
                ff=Feedforward(kS=0.0, kV=1.0, kA=0.0),
            ),
        ),
        imu=defs.imu,
    )
    odometry = FusedOdometry(
        imu=defs.imu, kinematics=kinematics, config=FusedOdometryConfig(bemf_trust=1.0)
    )
    motion_pid_config = UnifiedMotionPidConfig(
        angle_tolerance_rad=0.017,
        derivative_lpf_alpha=0.5,
        distance_kd=0.0,
        distance_ki=0.0,
        distance_kp=1.0,
        distance_tolerance_m=0.005,
        heading_kd=0.0,
        heading_ki=0.0,
        heading_kp=1.0,
        heading_min_scale=0.25,
        heading_recovery_error_rad=0.005,
        heading_saturation_derating_factor=0.85,
        heading_saturation_error_rad=0.01,
        heading_saturation_recovery_rate=0.05,
        integral_deadband=0.01,
        integral_max=10.0,
        lateral_heading_bias_gain=0.5,
        lateral_kd=0.0,
        lateral_ki=0.0,
        lateral_kp=1.0,
        lateral_reorient_threshold_m=0.15,
        max_heading_rate=3.0,
        max_linear_acceleration=1.0,
        min_angular_rate=0.1,
        min_speed_mps=0.05,
        output_max=10.0,
        output_min=-10.0,
        saturation_derating_factor=0.85,
        saturation_min_scale=0.1,
        saturation_recovery_rate=0.02,
    )
    missions = [PotatoMission()]
    setup_mission = SetupMission()
    shutdown_mission = ShutdownMission()
    width_cm = 13.0
    length_cm = 19.0
    rotation_center_forward_cm = -1.5
    rotation_center_strafe_cm = 0.0
    _sensor_positions = {
        defs.front_left_ir_sensor: SensorPosition(
            forward_cm=7.5, strafe_cm=3.3, clearance_cm=1.0
        ),
        defs.front_right_ir_sensor: SensorPosition(
            forward_cm=7.5, strafe_cm=-3.3, clearance_cm=1.0
        ),
    }
    _wheel_positions = {
        defs.front_left_motor: WheelPosition(forward_cm=6.0, strafe_cm=9.5),
        defs.front_right_motor: WheelPosition(forward_cm=6.0, strafe_cm=-9.5),
        defs.rear_left_motor: WheelPosition(forward_cm=-6.0, strafe_cm=9.5),
        defs.rear_right_motor: WheelPosition(forward_cm=-6.0, strafe_cm=-9.5),
    }


__all__ = ["Robot"]
