- M00SetupMission: setup
- M99ShutdownMission: shutdown
- M01GrabFirstPomsMission
- M02DriveDownAccesRampMission
- M03GrabSecondPomsMission
- M04AlignForLastPomsMission
- M05CollectLastPomsMission
- M06DriveToBasketsMission
- M07DropSortedPomsMission
- M08DropMachingPomsMission