front_left_motor:
  type: Motor
  port: 0
  inverted: false
  calibration:
    ticks_to_rad: 1.829585351653621e-05
    vel_lpf_alpha: 1.0
front_right_motor:
  type: Motor
  port: 1
  inverted: true
  calibration:
    ticks_to_rad: 1.7813664465062122e-05
    vel_lpf_alpha: 1.0
rear_left_motor:
  type: Motor
  port: 2
  inverted: false
  calibration:
    ticks_to_rad: 1.7250823646842606e-05
    vel_lpf_alpha: 1.0
rear_right_motor:
  type: Motor
  port: 3
  inverted: true
  calibration:
    ticks_to_rad: 1.7683641451385708e-05
    vel_lpf_alpha: 1.0
