shild:
  type: Servo
  port: 0
  positions:
    up: 65
    _45deg: 125
    down: 180
    normal_drive: 175
    above_pasked: 132
    grab_pasked: 153
pom_arm:
  type: Servo
  port: 1
  positions:
    down: 152
    above_pom: 135
    above_basket: 108
    up: 130
    start: 0
    high_up: 30
shild_graber:
  type: Servo
  port: 2
  positions:
    open: 70
    wide_open: 40
    closed: 145
pom_grab:
  type: Servo
  port: 3
  positions:
    closed: 10
    start: 30
    pom_width: 47
    slightly_open: 700
    open: 90
    wide_open: 110
    m05_collect_poms: 65