"""
===========================================================
 Project:   PackingBot
 Generated: 2026-02-08 15:37:25
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *

from src.steps.light_sensor_steps import frontside_forward_lineup_on_black, frontside_forward_drive_until_line
from src.hardware.defs import *
from src.steps.servo_steps import servo_pom_arm_up


class AlignForLastPomsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            drive_forward(20, 1.0),
            #push a blue pom to collect it later
            parallel(
                turn_right(90, speed=1.0),
                seq([
                    wait(1),
                    servo_pom_arm_up(),
                ]),
            ),

            #TODO may do the backward driving with a linefollow if it exists
            drive_backward(25, 1.0),
            wall_align_backward(1.0, 0.4)

            #align on black line
        ])