"""
===========================================================
 Project:   PackingBot
 Generated: 2026-01-30 20:24:46
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *
from src.hardware.defs import *
from src.steps.drive_over_step import frontside_forward_move_over_line
from src.steps.light_sensor_steps import frontside_forward_lineup_on_black
from src.steps.servo_steps import *


class GrabFirstPomsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            # drive infront of poms
            turn_left(90, 0.5),
            drive_backward(cm=2),
            #TODO use a linup, but until this shit wokes our robot will alighn it self on hops an prayers and the broken imu shit :(
            #frontside_forward_lineup_on_black(),
            #drive_backward(cm=3),
            strafe_left(cm=13),

            # push poms back
            drive_forward(cm=35),
            drive_backward(cm=35),

            servo_pom_grab_open(),
            servo_pom_arm_down(),

            # TODO: use the nice funktions
            #frontside_forward_move_over_line(forward_speed=1.0),
            #follow_line

            #get poms and close claw
            drive_forward(cm=70),
            servo_pom_grab_close(),
            servo_pom_arm_up(),

            #drop cube down
            strafe_right(cm=20),
            drive_forward(cm=10),

            strafe_left(cm=20),

            #TODO do som align on balck line to do shit right?
            strafe_left(cm=20),
        ])