"""
===========================================================
 Project:   PackingBot
 Generated: 2026-01-30 20:24:46
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *
from libstp.step.parallel import parallel

from src.hardware.defs import *
from src.steps.drive_over_step import frontside_forward_move_over_line
from src.steps.light_sensor_steps import *
from src.steps.servo_steps import *


class GrabFirstPomsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            # drive infront of poms
            turn_left(90, 1.0),
            drive_backward(3, 1.0),
            strafe_left(14, 1.0),
            # TODO use the nixe funciton here
            #simpl_frontside_forward_lineup_on_black(),
            #drive_forward(20,1.0),
            # FIXME delete the simple drive forward to be more accurate
            drive_forward(25,1.0),

            parallel(
                seq([ #drives backwards to prepear to set down the the claw
                    drive_backward(25, 1.0),
                ]),
                seq([ #repears the servo to move down while moving bacwards
                    servo_pom_arm_up(),
                    servo_pom_grab_open(),
                ]),
            ),
            servo_pom_arm_down(),

            #the poms collectin is done simultanisosly with
            #the drive_down_acces_ramp mission


        ])