"""
===========================================================
 Project:   PackingBot
 Generated: 2026-01-30 20:24:46
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *
from libstp.step.parallel import parallel

from src.hardware.defs import *
from src.steps.drive_over_step import frontside_forward_move_over_line
from src.steps.light_sensor_steps import *
from src.steps.servo_steps import *


class M02GrabFirstPomsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            # drive infront of poms
            strafe_right(20, 1.0),
            servo_shield_up(999),
            strafe_left(20, 1.0),

            parallel(
                seq([ #turn and prepare to set down the claw
                    turn_right(90, 1.0),
                ]),
                seq([ #prepares the servo to move down while moving backwards
                    servo_pom_arm_up(),
                    servo_pom_grab_open(),
                ]),
            ),
            drive_backward(5, 1),
            servo_pom_arm_down(),
            frontside_forward_drive_over_line(),
            strafe_left_until_black(Defs.front_right_light_sensor, 1.0),

            parallel(
                # get poms and close claw
                seq([
                    frontside_line_follow_right_edge(135, 1.0),  # drives down access ramp
                    single_line_follow_right_front_edge_until_line(),
                    parallel(
                        drive_forward(40, 1.0),
                        wall_align_forward(1.0, 0.5)
                        servo_pom_arm_high_up(),
                    )
                ]),
                seq([
                    #wait until we have collected all poms
                    wait_until_distance(35),
                    servo_pom_grab_close(999),
                    servo_pom_arm_up(),
                    servo_shield_up(999),
                ]),
                seq([
                    #wait until the claw is over the edge and put it back down
                    wait_until_distance(65),
                    servo_pom_arm_down(),
                ]),
                # close the claw a bit, so fully closing it is faster
                servo_pom_grab_slightly_open(999),
                servo_shield_down(999),
            ),
        ])