"""
===========================================================
 Project:   PackingBot
 Generated: 2026-03-10 20:32:51
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *
from src.hardware.defs import Defs

def line_follow(speed = 1.0):
    return strafe_follow_line_single(
        Defs.front.left,
        speed=speed,
        side=LineSide.LEFT,
        kp=0.5,
        kd=0.1,
    )


class M060DriveToBasketsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            strafe_left(speed=1.0).until(on_black(Defs.front.left)),

            #get rid of fist traffic conde
            turn_left().until(after_degrees(35) | after_seconds(0.7)),
            parallel(
                turn_to_heading_right(0, 1.0),
                Defs.pom_arm.high_up(150),
            ),

            #drive until line and 15cm higher
            line_follow().until(
                on_black(Defs.rear.right) > after_cm(15),
            ),

            #get rid of second traffic conde
            parallel(
                turn_right(degrees=10),
                Defs.pom_arm.down(150),
            ),
            turn_left().until(after_degrees(50) | after_seconds(1.0)),
            parallel(
                turn_to_heading_right(0, 1.0),
                Defs.pom_arm.start(90),
            ),

            #drive to first basket
            line_follow().until(
                after_seconds(1.3) > on_black(Defs.front.right) > after_cm(15)
            ),



        ])