"""
===========================================================
 Project:   PackingBot
 Generated: 2026-03-10 20:32:51
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *
from src.hardware.defs import Defs

def line_follow(speed = 1.0):
    return strafe_follow_line_single(
        Defs.front.left,
        speed=speed,
        side=LineSide.LEFT,
        kp=0.5,
        kd=0.0,
    )


class M060DriveToBasketsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            backround(
                Defs.shild.save_up(),
                Defs.pom_arm.start(),
            ),
            #TODO: replace the strafe with a diagonal with 20 deg to left
            strafe_left(speed=1.0).until(on_black(Defs.front.left)),

            #drive to baskets
            line_follow().until(
                over_line(Defs.rear.right) +
                over_line(Defs.rear.right) +
                after_cm(15)
            ),
        ])