"""
===========================================================
 Project:   PackingBot
 Generated: 2026-03-10 20:32:51
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *
from src.hardware.defs import Defs

def line_follow(speed = 1.0):
    return strafe_follow_line_single(
        Defs.front.left,
        speed=speed,
        side=LineSide.LEFT,
        kp=0.5,
        kd=0.1,
    )


class M06DriveToBasketsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            strafe_left(speed=1.0).until(on_black(Defs.front.left)),

            #get rid of fist traffic conde
            turn_left(degrees=35),
            parallel(
                turn_to_heading_right(0, 1.0),
                Defs.pom_arm.high_up(200),
            ),

            #drive until line and 15cm higher
            line_follow().until(
                on_black(Defs.rear.right) > after_cm(15),
            ),

            #get rid of second traffic conde
            parallel(
                turn_right(degrees=10),
                Defs.pom_arm.down(100),
            ),
            turn_left(degrees=50),
            parallel(
                turn_to_heading_right(0, 1.0),
                Defs.pom_arm.high_up(200),
            ),

            #TODO: fuse the two line_follows if it works again
            line_follow().until(
                on_black(Defs.front.right),
            ),
            strafe_follow_line_single(
                Defs.front.left,
                15,
                speed=1.0,
                side=LineSide.LEFT,
                kp=0.5,
                kd=0.1,
            ),

            #grab the one basket
            Defs.shild.above_pasked(),
            strafe_right(cm=1),
            Defs.shild.down(),

            #pull the basktet out
            strafe_left().until(
                on_black(Defs.front.right)
            ),
            Defs.shild.above_pasked(),
            strafe_left(cm=5),

            drive_forward().until(
                on_black(Defs.rear.right) >
                on_white(Defs.rear.right)
            ),

            strafe_right().until(
                on_black(Defs.front.left)
            ),
            Defs.shild_graber.open(),
            wait_for_seconds(0.5),
            parallel(
                Defs.shild_graber.closed(),
                Defs.shild.up(),
            ),

            #position to throw cubes down
            strafe_left().until(
                on_black(Defs.front.right) >
                on_white(Defs.front.right)
            ),
            #throw cubes down
            parallel(
                turn_to_heading_right(degrees=45),
                Defs.pom_arm.up(100),
            ),
            turn_left().until(after_seconds(0.5)),
            turn_to_heading_left(0),
            Defs.pom_arm.high_up(),

            #we now sand someware and baskets ar to the right of us :)


        ])