"""
===========================================================
 Project:   PackingBot
 Generated: 2026-02-08 17:32:19
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import Mission, Sequential, seq, strafe_left_until_black, drive_forward, strafe_right_until_white, turn_to_heading
from pycparser.c_ast import Default

from src.steps.servo_steps import servo_pom_arm_down, servo_pom_grab_wide_open
from src.hardware.defs import *


class M06CollectLastPomsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([

            drive_forward(5.0, 1.0),
            strafe_left_until_black(Defs.front_left_light_sensor,
                                    speed=0.3,
                                    confidence_threshold=0.3),

            strafe_right_until_white(Defs.front_left_light_sensor,
                                    speed=0.3,
                                    confidence_threshold=0.3),

            turn_to_heading(0, 1.0),
            servo_pom_grab_wide_open(),
        ])