"""Auto-generated by Raccoon Toolchain (Tobias Madlberger / RaccoonOS Team)"""

from raccoon import (
    AnalogSensor,
    DigitalSensor,
    IRSensor,
    Motor,
    MotorCalibration,
    SensorGroup,
    Servo,
    ServoPreset,
)
from raccoon import IMU as Imu


class Defs:
    imu = Imu()
    button = DigitalSensor(port=9)
    wait_for_light_sensor = AnalogSensor(port=5)
    front_left_light_sensor = IRSensor(port=0)
    front_right_light_sensor = IRSensor(port=1)
    rear_left_light_sensor = IRSensor(port=2)
    et_sensor = AnalogSensor(port=4)
    front = SensorGroup(left=front_left_light_sensor, right=front_right_light_sensor)
    rear = SensorGroup(left=rear_left_light_sensor)
    front_left_motor = Motor(
        port=0,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.8169604858855874e-05, vel_lpf_alpha=1.0
        ),
    )
    front_right_motor = Motor(
        port=1,
        inverted=True,
        calibration=MotorCalibration(
            ticks_to_rad=1.6710972295669667e-05, vel_lpf_alpha=1.0
        ),
    )
    rear_left_motor = Motor(
        port=2,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.6218771051845913e-05, vel_lpf_alpha=1.0
        ),
    )
    rear_right_motor = Motor(
        port=3,
        inverted=True,
        calibration=MotorCalibration(
            ticks_to_rad=1.647740302585203e-05, vel_lpf_alpha=1.0
        ),
    )
    arm_base = ServoPreset(
        Servo(port=0),
        positions={
            "_0deg": 110.3,
            "p90deg": 11.6,
            "max_left": -30,
            "m90deg": 196.2,
            "max_right": 207,
        },
    )
    arm_sholder = ServoPreset(
        Servo(port=1),
        positions={"max_down": 195.3, "_0deg": 169.2, "p90deg": 69, "max_up": 25},
        offset=22.4,
    )
    arm_elbow = ServoPreset(
        Servo(port=2),
        positions={
            "_0deg": 92.2,
            "p90deg": 187.3,
            "max_max": 208.0,
            "m90deg": -3.1,
            "max_minus": -25,
        },
    )
    arm_claw = ServoPreset(
        Servo(port=3),
        positions={
            "idle": 10,
            "open": 70,
            "full_open": 80,
            "grab": 10,
            "strong_grab": -10,
        },
    )
    analog_sensors = [
        wait_for_light_sensor,
        front_left_light_sensor,
        front_right_light_sensor,
        rear_left_light_sensor,
        et_sensor,
    ]
    wait_for_light_mode = "auto"


defs = Defs()

__all__ = ["Defs", "defs"]
