"""
===========================================================
 Project:   PackingBot
 Generated: 2026-02-17 12:42:04
===========================================================

Authors:
  • Tobias Madlberger (Scaffold / CLI Author)
  • RaccoonOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
"""

from libstp import (
    Drive,
    FusedOdometry,
    FusedOdometryConfig,
    GenericRobot,
    MecanumKinematics,
    SensorPosition,
    UnifiedMotionPidConfig,
    WheelPosition,
)

from src.hardware.defs import Defs


from src.missions.setup_mission import SetupMission
from src.missions.shutdown_mission import ShutdownMission
from src.missions.grab_first_poms_mission import GrabFirstPomsMission


class Robot(GenericRobot):
    defs = Defs()
    kinematics = MecanumKinematics(
        back_left_motor=defs.rear_left_motor,
        back_right_motor=defs.rear_right_motor,
        front_left_motor=defs.front_left_motor,
        front_right_motor=defs.front_right_motor,
        track_width=0.2,
        wheel_radius=0.0375,
        wheelbase=0.123,
    )
    odometry = FusedOdometry(
        imu=defs.imu, kinematics=kinematics, config=FusedOdometryConfig(bemf_trust=1.0)
    )
    motion_pid_config = UnifiedMotionPidConfig(
        distance_kd=0.5,
        distance_ki=0.0,
        distance_kp=1.0,
        heading_kd=0.2,
        heading_ki=0.0,
        heading_kp=1.0,
    )
    missions = [GrabFirstPomsMission()]
    setup_mission = SetupMission()
    shutdown_mission = ShutdownMission()


__all__ = ["Robot"]
