- M000SetupMission: setup
#- M010DriveToDrumsMission
- M020CollectDrumsMission
#- M030DriveToPipeMission
#- MEjectDrumsMission
#- M050DriveToOtherPipeMission
#- MEjectDrumsMission
- M999ShutdownMission: shutdown
#- M1009TestMission
