front_left_motor:
  type: Motor
  port: 0
  inverted: false
  calibration:
    ticks_to_rad: 1.948586498082425e-05
    vel_lpf_alpha: 1.0
front_right_motor:
  type: Motor
  port: 1
  inverted: true
  calibration:
    ticks_to_rad: 1.587361640374804e-05
    vel_lpf_alpha: 1.0
drum_motor:
  type: Motor
  port: 2
  inverted: false
  calibration:
    ticks_to_rad: 1.0
    vel_lpf_alpha: 1.0
servo_help_motor:
  type: Motor
  port: 3
  inverted: false
  calibration:
    ticks_to_rad: 1e-05
    vel_lpf_alpha: 1.0
