drum_pusher_servo:
  type: Servo
  port: 0
pom_remover_servo:
  type: Servo
  port: 3
  positions:
    start: 154.4
    push_first_orange_pom_away: 30
    standby: 145
lift_drums_servo:
  type: Servo
  port: 1
