drum_pusher_servo:
  type: Servo
  port: 0
  offset: 0
  positions:
    close: 10
    open: 180
    block_angle: 55
pom_remover_servo:
  type: Servo
  port: 3
  positions:
    start: 95
    right: 20
    r_cube: 50  #position to not touch the cube
    left: 180
    center: 100
    orange_pom_removel: 130

lift_drums_servo:
  type: Servo
  port: 1
  positions:
    up: 175       #a bit more thane 170° for better driving
    align_on_back: 70
    eject_position: 152
    seek_position: 162
    down: 5
    remove_D: 38
    remove_M: 70