from libstp.button import set_digital

"""
===========================================================
 Project:   tobi-test
 Generated: 2026-01-07 13:29:44
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""

from src.hardware.robot import Robot

robot = Robot()

import libstp.foundation as logging

#logging.set_global_level(logging.Level.trace)
# logging.set_file_level("turn.py", logging.Level.trace)
logging.set_file_level("linear_motion.cpp", logging.Level.trace)
#logging.set_file_level("fused_odometry.cpp", logging.Level.info)
#logging.set_file_level("drive.cpp", logging.Level.trace)

if __name__ == "__main__":
    set_digital(10)
    robot.start()
