"""
===========================================================
 Project:   PackingBot
 Generated: 2026-02-07 14:57:46
===========================================================

Authors:
  • Tobias Madlberger (Scaffold / CLI Author)
  • RaccoonOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
"""

from libstp import (
    AnalogSensor,
    DigitalSensor,
    Feedforward,
    IRSensor,
    Motor,
    MotorCalibration,
    PidGains,
    Servo,
)
from libstp import IMU as Imu


class Defs:
    imu = Imu()
    button = DigitalSensor(port=10)
    front_left_motor = Motor(
        port=1,
        inverted=False,
        calibration=MotorCalibration(
            ff=Feedforward(kS=0.165, kV=0.16505993860636586, kA=1e-06),
            pid=PidGains(kp=10.0, ki=10.0, kd=2.0),
            ticks_to_rad=0.004463102469338597,
            vel_lpf_alpha=0.8,
        ),
    )
    front_right_motor = Motor(
        port=0,
        inverted=True,
        calibration=MotorCalibration(
            ff=Feedforward(kS=0.22, kV=0.1415650287290876, kA=1e-06),
            pid=PidGains(kp=10.0, ki=10.0, kd=2.0),
            ticks_to_rad=0.004434681801506975,
            vel_lpf_alpha=0.8,
        ),
    )
    rear_left_motor = Motor(
        port=2,
        inverted=False,
        calibration=MotorCalibration(
            ff=Feedforward(kS=0.17, kV=0.16154924342153362, kA=1e-06),
            pid=PidGains(kp=10.0, ki=10.0, kd=2.0),
            ticks_to_rad=0.004624068630573387,
            vel_lpf_alpha=0.8,
        ),
    )
    rear_right_motor = Motor(
        port=3,
        inverted=True,
        calibration=MotorCalibration(
            ff=Feedforward(kS=0.18, kV=0.10116544412095624, kA=0.004394658054609205),
            pid=PidGains(kp=10.0, ki=10.0, kd=2.0),
            ticks_to_rad=0.0044333016794217694,
            vel_lpf_alpha=0.8,
        ),
    )
    rear_right_light_sensor = IRSensor(port=0)
    rear_left_light_sensor = IRSensor(port=1)
    wait_for_light_sensor = AnalogSensor(port=2)
    front_right_light_sensor = IRSensor(port=4)
    front_left_light_sensor = IRSensor(port=5)
    pom_arm = Servo(port=1)
    pom_grab = Servo(port=3)
    analog_sensors = [
        rear_right_light_sensor,
        rear_left_light_sensor,
        wait_for_light_sensor,
        front_right_light_sensor,
        front_left_light_sensor,
    ]


__all__ = ["Defs"]
