"""
===========================================================
 Project:   PackingBot
 Generated: 2026-03-07 13:53:17
===========================================================

Authors:
  • Tobias Madlberger (Scaffold / CLI Author)
  • RaccoonOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
"""

from libstp import AnalogSensor, DigitalSensor, IRSensor, Motor, MotorCalibration, Servo
from libstp import IMU as Imu


class Defs:
    imu = Imu()
    button = DigitalSensor(port=10)
    front_left_motor = Motor(
        port=1,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.5759054491255986e-05, vel_lpf_alpha=1.0
        ),
    )
    front_right_motor = Motor(
        port=0,
        inverted=True,
        calibration=MotorCalibration(
            ticks_to_rad=1.5528613583072952e-05, vel_lpf_alpha=1.0
        ),
    )
    rear_left_motor = Motor(
        port=2,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.575270976731316e-05, vel_lpf_alpha=1.0
        ),
    )
    rear_right_motor = Motor(
        port=3,
        inverted=True,
        calibration=MotorCalibration(
            ticks_to_rad=1.590032818867565e-05, vel_lpf_alpha=1.0
        ),
    )
    rear_right_light_sensor = IRSensor(port=1)
    wait_for_light_sensor = AnalogSensor(port=2)
    front_right_light_sensor = IRSensor(port=4)
    front_left_light_sensor = IRSensor(port=5)
    shild = Servo(port=0)
    pom_arm = Servo(port=1)
    shild_graber = Servo(port=2)
    pom_grab = Servo(port=3)
    analog_sensors = [
        rear_right_light_sensor,
        wait_for_light_sensor,
        front_right_light_sensor,
        front_left_light_sensor,
    ]


__all__ = ["Defs"]
