"""
===========================================================
 Project:   PackingBot
 Generated: 2026-03-13 19:18:45
===========================================================

Authors:
  • Tobias Madlberger (Scaffold / CLI Author)
  • RaccoonOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
"""

from libstp import (
    AnalogSensor,
    DigitalSensor,
    IRSensor,
    Motor,
    MotorCalibration,
    SensorGroup,
    Servo,
    ServoPreset,
)
from libstp import IMU as Imu


class Defs:
    imu = Imu()
    button = DigitalSensor(port=10)
    rear_right_light_sensor = IRSensor(port=1)
    wait_for_light_sensor = AnalogSensor(port=2)
    front_right_light_sensor = IRSensor(port=4)
    front_left_light_sensor = IRSensor(port=5)
    front = SensorGroup(left=front_left_light_sensor, right=front_right_light_sensor)
    rear = SensorGroup(right=rear_right_light_sensor)
    front_left_motor = Motor(
        port=1,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.5560805748235626e-05, vel_lpf_alpha=1.0
        ),
    )
    front_right_motor = Motor(
        port=0,
        inverted=True,
        calibration=MotorCalibration(
            ticks_to_rad=1.519272038332997e-05, vel_lpf_alpha=1.0
        ),
    )
    rear_left_motor = Motor(
        port=2,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.5739416999801032e-05, vel_lpf_alpha=1.0
        ),
    )
    rear_right_motor = Motor(
        port=3,
        inverted=True,
        calibration=MotorCalibration(
            ticks_to_rad=1.574463315013559e-05, vel_lpf_alpha=1.0
        ),
    )
    shild = ServoPreset(Servo(port=0), positions={"up": 86, "down": 156})
    pom_arm = ServoPreset(
        Servo(port=1),
        positions={
            "down": 10,
            "above_pom": 55,
            "up": 105,
            "start": 160,
            "high_up": 165,
        },
    )
    shild_graber = ServoPreset(
        Servo(port=2), positions={"open": 70, "wide_open": 40, "closed": 135}
    )
    pom_grab = ServoPreset(
        Servo(port=3),
        positions={
            "closed": 0,
            "start": 30,
            "pom_width": 55,
            "slightly_open": 75,
            "open": 90,
            "wide_open": 125,
        },
    )
    analog_sensors = [
        rear_right_light_sensor,
        wait_for_light_sensor,
        front_right_light_sensor,
        front_left_light_sensor,
    ]


__all__ = ["Defs"]
