"""
===========================================================
 Project:   PackingBot
 Generated: 2026-03-03 19:28:28
===========================================================

Authors:
  • Tobias Madlberger (Scaffold / CLI Author)
  • RaccoonOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
"""

from libstp import (
    AxisConstraints,
    AxisVelocityControlConfig,
    ChassisVelocityControlConfig,
    Drive,
    Feedforward,
    FusedOdometry,
    FusedOdometryConfig,
    GenericRobot,
    MecanumKinematics,
    PidConfig,
    PidGains,
    SensorPosition,
    UnifiedMotionPidConfig,
    WheelPosition,
)

from src.hardware.defs import Defs


from src.missions.m01_setup_mission import M01SetupMission
from src.missions.m99_shutdown_mission import M99ShutdownMission
from src.missions.m02_grab_first_poms_mission import M02GrabFirstPomsMission
from src.missions.m03_drive_down_acces_ramp_mission import M03DriveDownAccesRampMission
from src.missions.m04_grab_second_poms_mission import M04GrabSecondPomsMission
from src.missions.m05_align_for_last_poms_mission import M05AlignForLastPomsMission
from src.missions.m06_collect_last_poms_mission import M06CollectLastPomsMission


def _build_chassis_vel_config(vx=None, vy=None, wz=None):
    cfg = ChassisVelocityControlConfig()
    if vx is not None:
        cfg.vx = vx
    if vy is not None:
        cfg.vy = vy
    if wz is not None:
        cfg.wz = wz
    return cfg


class Robot(GenericRobot):
    defs = Defs()
    kinematics = MecanumKinematics(
        back_left_motor=defs.rear_left_motor,
        back_right_motor=defs.rear_right_motor,
        front_left_motor=defs.front_left_motor,
        front_right_motor=defs.front_right_motor,
        track_width=0.2,
        wheel_radius=0.0375,
        wheelbase=0.125,
    )
    drive = Drive(
        kinematics=kinematics,
        vel_config=_build_chassis_vel_config(
            vx=AxisVelocityControlConfig(
                pid=PidGains(kp=0.137793, ki=1.108274, kd=0.010895),
                ff=Feedforward(kS=0.0, kV=1.0, kA=0.0),
            ),
            vy=AxisVelocityControlConfig(
                pid=PidGains(kp=0.0, ki=0.0, kd=0.0),
                ff=Feedforward(kS=0.0, kV=1.0, kA=0.0),
            ),
            wz=AxisVelocityControlConfig(
                pid=PidGains(kp=0.0, ki=0.0, kd=0.0),
                ff=Feedforward(kS=0.0, kV=1.0, kA=0.0),
            ),
        ),
        imu=defs.imu,
    )
    odometry = FusedOdometry(
        imu=defs.imu, kinematics=kinematics, config=FusedOdometryConfig(bemf_trust=1.0)
    )
    motion_pid_config = UnifiedMotionPidConfig(
        distance=PidConfig(
            kp=0.9375,
            ki=0.0,
            kd=0.1562,
            integral_max=10.0,
            integral_deadband=0.01,
            derivative_lpf_alpha=0.5,
            output_min=-10.0,
            output_max=10.0,
        ),
        heading=PidConfig(
            kp=2.0625,
            ki=0.0,
            kd=0.2,
            integral_max=10.0,
            integral_deadband=0.01,
            derivative_lpf_alpha=0.5,
            output_min=-10.0,
            output_max=10.0,
        ),
        velocity_ff=1.0,
        distance_tolerance_m=0.005,
        angle_tolerance_rad=0.017,
        saturation_derating_factor=0.85,
        saturation_min_scale=0.2,
        saturation_recovery_rate=0.02,
        saturation_hold_cycles=5,
        saturation_recovery_threshold=0.95,
        heading_saturation_derating_factor=0.85,
        heading_min_scale=0.25,
        heading_recovery_rate=0.05,
        heading_saturation_error_rad=0.01,
        heading_recovery_error_rad=0.005,
        linear=AxisConstraints(
            max_velocity=0.2139, acceleration=0.9402, deceleration=1.6644
        ),
        lateral=AxisConstraints(
            max_velocity=0.2209, acceleration=0.6485, deceleration=0.4498
        ),
        angular=AxisConstraints(
            max_velocity=1.8027, acceleration=2.4758, deceleration=17.4353
        ),
    )
    missions = [
        M02GrabFirstPomsMission(),
        M03DriveDownAccesRampMission(),
        M04GrabSecondPomsMission(),
        M05AlignForLastPomsMission(),
        M06CollectLastPomsMission(),
    ]
    setup_mission = M01SetupMission()
    shutdown_mission = M99ShutdownMission()
    width_cm = 23.5
    length_cm = 29.6
    rotation_center_forward_cm = 3.7
    rotation_center_strafe_cm = 0.0
    _sensor_positions = {
        defs.rear_right_light_sensor: SensorPosition(
            forward_cm=-12.2, strafe_cm=-12.25, clearance_cm=0
        ),
        defs.front_right_light_sensor: SensorPosition(
            forward_cm=14.2, strafe_cm=-2.95, clearance_cm=0
        ),
        defs.front_left_light_sensor: SensorPosition(
            forward_cm=14.2, strafe_cm=7.75, clearance_cm=0
        ),
    }
    _wheel_positions = {
        defs.front_left_motor: WheelPosition(forward_cm=6.25, strafe_cm=10.0),
        defs.front_right_motor: WheelPosition(forward_cm=6.25, strafe_cm=-10.0),
        defs.rear_left_motor: WheelPosition(forward_cm=-6.25, strafe_cm=10.0),
        defs.rear_right_motor: WheelPosition(forward_cm=-6.25, strafe_cm=-10.0),
    }


__all__ = ["Robot"]
