from .missions.setup_mission import SetupMission
from .missions.shutdown_mission import ShutdownMission
from .missions.grab_first_poms_mission import GrabFirstPomsMission
from .missions.push_crate_mission import PushCrateMission
from .missions.drive_down_acces_ramp_mission import DriveDownAccesRampMission
"""
===========================================================
 Project:   PackingBot
 Generated: 2026-01-29 14:21:31
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""

from src.hardware.robot import Robot
import libstp.foundation as logging

robot = Robot()

#logging.set_file_level("fused_odometry.cpp", logging.Level.trace),

if __name__ == "__main__":
   robot.start()
