- M000SetupMission: setup
- M010DriveToConeMission
- M020CollectConeMission
- M025CollectSecondConeMission
- M027DriveToBotguyMission
- M030CollectBotguyMission
- M040DriveToRampMission
- M050DriveToStartingBoxMission
- M060DropConeesMission
