claw_servo:
  type: Servo
  port: 2
  positions:
    closed: 154
    half_open: 70
    open: 45
    botguy_open: 90
    botguy_closed: 130
cone_arm_servo:
  type: Servo
  port: 0
  positions:
    container_pos: 34
    down: 168
    _20deg: 156
    _45deg: 136
    _90deg: 75
    handl_hight: 142
    botguy_head_hight: 150
