claw_servo:
  type: Servo
  port: 2
  positions:
    closed: 154
    half_open: 75
    open: 45
cone_arm_servo:
  type: Servo
  port: 1
  positions:
    up: 28
    down: 162
    slight_up: 150
    more_slight_up: 130