claw_servo:
  type: Servo
  port: 2
  positions:
    closed: 154
    half_open: 75
    open: 45
cone_arm_servo:
  type: Servo
  port: 1
  positions:
    container_pos: 34
    down: 168
    _20deg: 156
    _45deg: 136