"""
===========================================================
 Project:   PackingBot
 Generated: 2026-01-30 20:24:46
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *
from libstp.step.parallel import parallel

from src.hardware.defs import *
from src.steps.drive_over_step import frontside_forward_move_over_line
from src.steps.light_sensor_steps import frontside_forward_lineup_on_black
from src.steps.servo_steps import *


class GrabFirstPomsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            # drive infront of poms
            turn_left(90, 1.0),
            strafe_left(11, 1.0),
            drive_backward(cm=5),
            frontside_forward_lineup_on_black(),
            drive_forward(5,1.0),
            drive_backward(13, 1.0),

            # push poms back
            #drive_forward(cm=35),
            #drive_backward(cm=35),

            servo_pom_grab_open(),
            servo_pom_arm_down(),

            # TODO: use the nice funktions
            #frontside_forward_move_over_line(forward_speed=1.0),
            #follow_line

            #get poms and close claw
            #drive_forward(cm=20),
            #put the following 3 commands in a parallel if parallel is fixed
            #strafe_until_black(Defs.front_left_light_sensor, 1.0),
            #seq([
            #    servo_pom_grab_close(),
            #    servo_pom_grab_open(),
            #]),
            # ---
            drive_forward(cm=51),

            servo_pom_grab_close(),
            servo_pom_arm_up(),

        ])