"""
===========================================================
 Project:   PackingBot
 Generated: 2026-02-06 16:39:07
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *
from src.hardware.defs import Defs
from src.steps.servo_steps import *
from src.steps.light_sensor_steps import frontside_forward_lineup_on_black, backside_right_starfe_until_black, backside_backward_drive_until_line, backside_left_starfe_until_black

#class M03DriveDownAccesRampMission(Mission):
#    def sequence(self) -> Sequential:
#        return seq([
#            # drive infornt of pom
#            switch_calibration_set("default"),
#            drive_forward(25),
#            wall_align_forward(1.0, 0.5),
#            backside_backward_drive_until_line(),
#            #turn_right(90, 1.0),
#            #turn_to_heading(180, 1.0),
#            turn_right(90, 1.0),
#            wall_align_backward(1.0, 0.4),
#        ])


class M03DriveDownAccesRampMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            # drive infornt of pom
            switch_calibration_set("default"),

            turn_to_heading(180, 1.0),
            backside_right_starfe_until_black(),
            turn_to_heading(180, 1.0),

            wall_align_backward(1.0, 0.4, 0.1, 1.0), # TODO: put the max drive time to 0.7
            mark_heading_reference(),  # mark heading for use in drive down acess ramp

            drive_forward(2, 1.0),

        ])
