"""
===========================================================
 Project:   PackingBot
 Generated: 2026-02-06 16:39:07
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *
from src.hardware.defs import Defs
from src.steps.servo_steps import *
from src.steps.light_sensor_steps import frontside_forward_lineup_on_black


class M03DriveDownAccesRampMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            # drive infornt of poms
            turn_right(90, 1.0),
            strafe_right_until_black(Defs.rear_right_light_sensor, 0.3),
            frontside_forward_lineup_on_black(),
            drive_backward(10, 1.0),
            wall_align_backward(0.7, 0.4),
        ])