"""
===========================================================
 Project:   PackingBot
 Generated: 2026-02-07 17:09:49
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *

from src.hardware.defs import Defs
from src.steps.light_sensor_steps import frontside_forward_drive_until_line
from src.steps.servo_steps import *


class M04GrabSecondPomsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            parallel( #align on poms and put the claw down
                strafe_left_until_white(Defs.front_right_light_sensor, 0.3),
                servo_pom_arm_above_pom(speed=200),
            ),
            servo_pom_grab_slightly_open(speed=300),

            parallel(
                servo_pom_arm_down(),
                servo_pom_grab_open(),
            ),

            parallel(
                servo_pom_grab_pom_width(),
                frontside_forward_drive_until_line(),
            ),

            servo_pom_grab_close(999),
        ])