"""
===========================================================
 Project:   PackingBot
 Generated: 2026-02-08 17:32:19
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import Mission, Sequential, seq, strafe_left_until_black, drive_forward
from pycparser.c_ast import Default

from src.steps.light_sensor_steps import left_starfe_until_black
from src.steps.servo_steps import servo_pom_arm_down, servo_pom_grab_wide_open
from src.hardware.defs import *


class M06CollectLastPomsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            drive_forward(0.5, 1.0),
            strafe_left_until_black(Defs.front_left_light_sensor,
                                    speed=0.3,
                                    confidence_threshold=0.3),
            #left_starfe_until_black(threshold=0.3, speed = 0.3),
            servo_pom_arm_down(),
            servo_pom_grab_wide_open(),
        ])