"""
===========================================================
 Project:   tobi-test
 Generated: 2026-02-20 19:08:58
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import Mission, Sequential, seq, drive_forward


class DriveToDrumsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            drive_forward(20, 1.0),
        ])