"""
===========================================================
 Project:   {{ project_name }}
 Generated: {{ generated_at }}
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""

from libstp import *

from src.steps.drum_collector import calibrate_drum_collector
from src.steps.drum_lifting_step import *

class M00SetupMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            drum_lifting_up(slow_mode=False),
            calibrate(distance_cm=50),
            drum_lifting_down(),
            calibrate_drum_collector(calibration_time=2.0),
        ])
