"""
===========================================================
 Project:   tobi-test
 Generated: 2026-01-08 10:26:41
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
import math

from libstp import seq, Mission, drive_forward, turn_left, Turn
from libstp.motion import TurnConfig
from libstp.step.motion import measure_max_angular_velocity
from libstp.step.motion import auto_tune_turn, motor_response_test

class PotatoMission(Mission):
    def sequence(self) -> "Step":
        return seq([            
            open_drum_pusher(),
            wait_for_checkpoint(11),
            close_drum_pusher(),
            drum_retreat(),
        
            open_drum_pusher(),
            wait_for_checkpoint(10 + 8),
            close_drum_pusher(),
            drum_retreat(),
            
            open_drum_pusher(),
            wait_for_checkpoint(10 + 7 + 8),
            close_drum_pusher(),
            drum_retreat(),
            
            open_drum_pusher(),
            wait_for_checkpoint(10 + 7 + 7 + 8),
            close_drum_pusher(),
            drum_retreat(),
            
            open_drum_pusher(),
            wait_for_checkpoint(10 + 7 + 7 + 7 + 8),
            close_drum_pusher(),
            drum_retreat(),
            
            open_drum_pusher(),
            wait_for_checkpoint(10 + 7 + 7 + 7 + 7 + 8),
            close_drum_pusher(),
            drum_retreat(),
            
            open_drum_pusher(),
            wait_for_checkpoint(10 + 7 + 7 + 7 + 7 + 7 + 8),
            close_drum_pusher(),
            drum_retreat(),
            
            open_drum_pusher(),
            wait_for_checkpoint(10 + 7 + 7 + 7 + 7 + 7 + 7 + 8),
            close_drum_pusher(),
            drum_retreat(),
        ])
