"""
===========================================================
 Project:   {{ project_name }}
 Generated: {{ generated_at }}
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""

from libstp import Mission, Sequential, seq, calibrate_distance, calibrate, wait_for_button, loop_for


class SetupMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            loop_for(
                calibrate(distance_cm=50), iterations=5
            ),

            # calibrate_wait_for_light(Defs.front_left_ir_sensor)
            wait_for_button()
        ])
