"""
===========================================================
 Project:   {{ project_name }}
 Generated: {{ generated_at }}
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""

from libstp import Mission, Sequential, seq, wait_for_button

from src.steps.drum_collector import calibrate_drum_collector


class SetupMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            # loop_for(
            #     calibrate(distance_cm=50), iterations=5
            # ),

            # calibrate_wait_for_light(Defs.front_left_ir_sensor)
            calibrate_drum_collector(calibration_time=2.0),
            wait_for_button()
        ])
