"""Auto-generated by Raccoon Toolchain (Tobias Madlberger / RaccoonOS Team)"""

from libstp import (
    AnalogSensor,
    DigitalSensor,
    IRSensor,
    Motor,
    MotorCalibration,
    SensorGroup,
    Servo,
    ServoPreset,
)
from libstp import IMU as Imu


class Defs:
    imu = Imu()
    button = DigitalSensor(port=10)
    rear_right_light_sensor = IRSensor(port=1)
    wait_for_light_sensor = AnalogSensor(port=2)
    front_right_light_sensor = IRSensor(port=4)
    front_left_light_sensor = IRSensor(port=5)
    front = SensorGroup(left=front_left_light_sensor, right=front_right_light_sensor)
    rear = SensorGroup(right=rear_right_light_sensor)
    front_left_motor = Motor(
        port=1,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.6505581568850232e-05, vel_lpf_alpha=1.0
        ),
    )
    front_right_motor = Motor(
        port=0,
        inverted=True,
        calibration=MotorCalibration(
            ticks_to_rad=1.606628665936283e-05, vel_lpf_alpha=1.0
        ),
    )
    rear_left_motor = Motor(
        port=2,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.6499452123784625e-05, vel_lpf_alpha=1.0
        ),
    )
    rear_right_motor = Motor(
        port=3,
        inverted=True,
        calibration=MotorCalibration(
            ticks_to_rad=1.659537114430376e-05, vel_lpf_alpha=1.0
        ),
    )
    shild = ServoPreset(
        Servo(port=0),
        positions={
            "up": 65,
            "_45deg": 125,
            "down": 180,
            "normal_drive": 175,
            "above_pasked": 132,
            "grab_pasked": 153,
        },
    )
    pom_arm = ServoPreset(
        Servo(port=1),
        positions={
            "down": 152,
            "above_pom": 135,
            "above_basket": 108,
            "up": 130,
            "start": 0,
            "high_up": 30,
        },
    )
    shild_graber = ServoPreset(
        Servo(port=2), positions={"open": 70, "wide_open": 40, "closed": 145}
    )
    pom_grab = ServoPreset(
        Servo(port=3),
        positions={
            "closed": 40,
            "start": 30,
            "pom_width": 87,
            "slightly_open": 100,
            "open": 120,
            "wide_open": 140,
            "m05_collect_poms": 125,
        },
    )
    analog_sensors = [
        rear_right_light_sensor,
        wait_for_light_sensor,
        front_right_light_sensor,
        front_left_light_sensor,
    ]


__all__ = ["Defs"]
