"""
===========================================================
 Project:   PackingBot
 Generated: 2026-03-21 10:23:35
===========================================================

Authors:
  • Tobias Madlberger (Scaffold / CLI Author)
  • RaccoonOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
"""

from libstp import (
    AnalogSensor,
    DigitalSensor,
    IRSensor,
    Motor,
    MotorCalibration,
    SensorGroup,
    Servo,
    ServoPreset,
)
from libstp import IMU as Imu


class Defs:
    imu = Imu()
    button = DigitalSensor(port=10)
    rear_right_light_sensor = IRSensor(port=1)
    wait_for_light_sensor = AnalogSensor(port=1)
    front_right_light_sensor = IRSensor(port=4)
    front_left_light_sensor = IRSensor(port=5)
    front = SensorGroup(left=front_left_light_sensor, right=front_right_light_sensor)
    rear = SensorGroup(right=rear_right_light_sensor)
    front_left_motor = Motor(
        port=1,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.6409346766266992e-05, vel_lpf_alpha=1.0
        ),
    )
    front_right_motor = Motor(
        port=0,
        inverted=True,
        calibration=MotorCalibration(
            ticks_to_rad=1.5821968220392163e-05, vel_lpf_alpha=1.0
        ),
    )
    rear_left_motor = Motor(
        port=2,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.6534108046411276e-05, vel_lpf_alpha=1.0
        ),
    )
    rear_right_motor = Motor(
        port=3,
        inverted=True,
        calibration=MotorCalibration(
            ticks_to_rad=1.633047904459888e-05, vel_lpf_alpha=1.0
        ),
    )
    shild = ServoPreset(
        Servo(port=0),
        positions={
            "up": 65,
            "_45deg": 125,
            "down": 180,
            "normal_drive": 175,
            "above_pasked": 135,
            "grab_pasked": 153,
        },
    )
    pom_arm = ServoPreset(
        Servo(port=1),
        positions={
            "down": 152,
            "above_pom": 135,
            "above_basket": 108,
            "up": 140,
            "start": 0,
            "high_up": 0,
        },
    )
    shild_graber = ServoPreset(
        Servo(port=2), positions={"open": 70, "wide_open": 40, "closed": 145}
    )
    pom_grab = ServoPreset(
        Servo(port=3),
        positions={
            "closed": 40,
            "start": 30,
            "pom_width": 87,
            "slightly_open": 100,
            "open": 120,
            "wide_open": 140,
            "magic_val_for_m06": 120,
        },
    )
    analog_sensors = [
        rear_right_light_sensor,
        wait_for_light_sensor,
        front_right_light_sensor,
        front_left_light_sensor,
    ]


__all__ = ["Defs"]
