"""Auto-generated by Raccoon Toolchain (Tobias Madlberger / RaccoonOS Team)"""

from libstp import (
    AnalogSensor,
    DigitalSensor,
    IRSensor,
    Motor,
    MotorCalibration,
    SensorGroup,
    Servo,
    ServoPreset,
)
from libstp import IMU as Imu


class Defs:
    imu = Imu()
    button = DigitalSensor(port=10)
    distance_sensor = AnalogSensor(port=0)
    rear_right_light_sensor = IRSensor(port=1)
    wait_for_light_sensor = AnalogSensor(port=2)
    front_right_light_sensor = IRSensor(port=4)
    front_left_light_sensor = IRSensor(port=5)
    front = SensorGroup(left=front_left_light_sensor, right=front_right_light_sensor)
    rear = SensorGroup(right=rear_right_light_sensor)
    front_left_motor = Motor(
        port=1,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.6575786290431456e-05, vel_lpf_alpha=1.0
        ),
    )
    front_right_motor = Motor(
        port=0,
        inverted=True,
        calibration=MotorCalibration(
            ticks_to_rad=1.6015429623653166e-05, vel_lpf_alpha=1.0
        ),
    )
    rear_left_motor = Motor(
        port=2,
        inverted=False,
        calibration=MotorCalibration(
            ticks_to_rad=1.638079795430057e-05, vel_lpf_alpha=1.0
        ),
    )
    rear_right_motor = Motor(
        port=3,
        inverted=True,
        calibration=MotorCalibration(
            ticks_to_rad=1.668356144870973e-05, vel_lpf_alpha=1.0
        ),
    )
    shild = ServoPreset(
        Servo(port=0),
        positions={
            "up": 65,
            "save_up": 75,
            "_45deg": 125,
            "down": 180,
            "normal_drive": 175,
            "above_pasked": 132,
            "grab_pasked": 165,
            "m06_above_paskted": 140,
            "m06_on_paskted": 150,
        },
    )
    pom_arm = ServoPreset(
        Servo(port=1),
        positions={
            "down": 152,
            "above_pom": 135,
            "above_basket": 145,
            "up": 135,
            "drop_poms_pos": 90,
            "start": 5,
            "high_up": 30,
        },
    )
    shild_graber = ServoPreset(
        Servo(port=2), positions={"open": 90, "wide_open": 40, "closed": 150}
    )
    pom_grab = ServoPreset(
        Servo(port=3),
        positions={
            "closed": 10,
            "start": 30,
            "pom_width": 47,
            "slightly_open": 100,
            "open": 120,
            "wide_open": 140,
            "m05_collect_poms": 105,
        },
        offset=5.0,
    )
    analog_sensors = [
        distance_sensor,
        rear_right_light_sensor,
        wait_for_light_sensor,
        front_right_light_sensor,
        front_left_light_sensor,
    ]


defs = Defs()

__all__ = ["Defs", "defs"]
