"""
===========================================================
 Project:   PackingBot
 Generated: 2026-01-31 16:46:02
===========================================================

Authors:
  • Tobias Madlberger (Scaffold / CLI Author)
  • RaccoonOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
"""

from libstp import Drive, FusedOdometry, MecanumKinematics, MotionLimits

from libstp import GenericRobot

from src.hardware.defs import Defs


from src.missions.setup_mission import SetupMission
from src.missions.shutdown_mission import ShutdownMission
from src.missions.grab_first_poms_mission import GrabFirstPomsMission


class Robot(GenericRobot):
    defs = Defs()
    kinematics = MecanumKinematics(
        back_left_motor=defs.rear_left_motor,
        back_right_motor=defs.rear_right_motor,
        front_left_motor=defs.front_left_motor,
        front_right_motor=defs.front_right_motor,
        max_acceleration=42999999966.667,
        max_velocity=5339999999993.333,
        track_width=0.2,
        wheel_radius=0.0375,
        wheelbase=0.12,
    )
    drive = Drive(
        kinematics=kinematics,
        chassis_lim=MotionLimits(max_omega=200000000.0, max_v=20000000.0),
    )
    odometry = FusedOdometry(imu=defs.imu, kinematics=kinematics)
    missions = [GrabFirstPomsMission()]
    setup_mission = SetupMission()
    shutdown_mission = ShutdownMission()


__all__ = ["Robot"]
