"""
===========================================================
 Project:   PackingBot
 Generated: 2026-02-06 20:28:19
===========================================================

Authors:
  • Tobias Madlberger (Scaffold / CLI Author)
  • RaccoonOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
"""

from libstp import (
    Drive,
    FusedOdometry,
    FusedOdometryConfig,
    GenericRobot,
    MecanumKinematics,
    MotionLimits,
    SensorPosition,
    UnifiedMotionPidConfig,
    WheelPosition,
)

from src.hardware.defs import Defs


from src.missions.setup_mission import SetupMission
from src.missions.shutdown_mission import ShutdownMission
from src.missions.test_mission import TestMission


class Robot(GenericRobot):
    defs = Defs()
    kinematics = MecanumKinematics(
        back_left_motor=defs.rear_left_motor,
        back_right_motor=defs.rear_right_motor,
        front_left_motor=defs.front_left_motor,
        front_right_motor=defs.front_right_motor,
        max_acceleration=42999999966.667,
        max_velocity=5339999999993.333,
        track_width=0.2,
        wheel_radius=0.0375,
        wheelbase=0.12300000000000001,
    )
    drive = Drive(
        kinematics=kinematics,
        chassis_lim=MotionLimits(max_omega=200000000.0, max_v=20000000.0),
    )
    odometry = FusedOdometry(
        imu=defs.imu, kinematics=kinematics, config=FusedOdometryConfig(bemf_trust=0.9)
    )
    motion_pid_config = UnifiedMotionPidConfig(
        angle_tolerance_rad=0.02,
        derivative_lpf_alpha=0.1,
        distance_kd=0.0,
        distance_ki=0.0,
        distance_kp=2.0,
        distance_tolerance_m=0.01,
        heading_kd=0.0,
        heading_ki=0.0,
        heading_kp=3.0,
        heading_min_scale=0.25,
        heading_recovery_error_rad=0.005,
        heading_saturation_derating_factor=0.85,
        heading_saturation_error_rad=0.01,
        heading_saturation_recovery_rate=0.05,
        integral_deadband=0.01,
        integral_max=10.0,
        lateral_heading_bias_gain=0.5,
        lateral_kd=0.0,
        lateral_ki=0.0,
        lateral_kp=2.0,
        lateral_reorient_threshold_m=0.15,
        max_angular_acceleration=3.0,
        max_heading_rate=3.0,
        max_linear_acceleration=1.0,
        min_angular_rate=0.1,
        min_speed_mps=0.05,
        output_max=10.0,
        output_min=-10.0,
        saturation_derating_factor=0.85,
        saturation_min_scale=0.1,
        saturation_recovery_rate=0.02,
    )
    missions = [TestMission()]
    setup_mission = SetupMission()
    shutdown_mission = ShutdownMission()
    width_cm = 23.6
    length_cm = 30.0
    rotation_center_forward_cm = 2.15
    rotation_center_strafe_cm = 0.0
    _sensor_positions = {
        defs.rear_right_light_sensor: SensorPosition(
            forward_cm=-11.0, strafe_cm=-8.5, clearance_cm=1.0
        ),
        defs.rear_left_light_sensor: SensorPosition(
            forward_cm=-11.0, strafe_cm=8.5, clearance_cm=1.0
        ),
        defs.front_right_light_sensor: SensorPosition(
            forward_cm=14.0, strafe_cm=-8.5, clearance_cm=1.0
        ),
        defs.front_left_light_sensor: SensorPosition(
            forward_cm=14.0, strafe_cm=8.5, clearance_cm=1.0
        ),
    }
    _wheel_positions = {
        defs.front_left_motor: WheelPosition(forward_cm=6.15, strafe_cm=10.0),
        defs.front_right_motor: WheelPosition(forward_cm=6.15, strafe_cm=-10.0),
        defs.rear_left_motor: WheelPosition(forward_cm=-6.15, strafe_cm=10.0),
        defs.rear_right_motor: WheelPosition(forward_cm=-6.15, strafe_cm=-10.0),
    }


__all__ = ["Robot"]
