"""
===========================================================
 Project:   PackingBot
 Generated: 2026-02-06 16:39:07
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from os import wait

from libstp import Mission, Sequential, seq, strafe_until_black, strafe_left, drive_until_black, drive_forward, \
    strafe_right_until_black, strafe_left_until_black

from src.hardware.defs import Defs


class DriveDownAccesRampMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            strafe_left_until_black(Defs.front_left_light_sensor, 0.5),
            wait(1),
            strafe_left(1, 0.5),
            drive_forward(115.0,0.5)
        ])