"""
===========================================================
 Project:   PackingBot
 Generated: 2026-02-06 16:39:07
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *
from src.hardware.defs import Defs


class DriveDownAccesRampMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            #strafe_left_until_black(Defs.front_left_light_sensor, 0.5),
            strafe_left_lineup_on_black(Defs.front_left_light_sensor, Defs.rear_left_light_sensor, 0.4),
            strafe_left(5, 1.0),
            wait(1),
            drive_forward(115.0,0.5)
        ])