"""
===========================================================
 Project:   PackingBot
 Generated: 2026-02-07 17:09:49
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import Mission, Sequential, seq, turn_right, strafe_right_until_black, drive_backward

from src.hardware.defs import Defs


class GrabSecondPomsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            turn_right(90,1.0),
            strafe_right_until_black(Defs.front_right_light_sensor, 1.0),
            drive_backward(10, 1.0)
        ])