"""
===========================================================
 Project:   PackingBot
 Generated: 2026-01-30 20:24:46
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *
from libstp.step.parallel import parallel

from src.hardware.defs import *
from src.steps.drive_over_step import frontside_forward_move_over_line
from src.steps.light_sensor_steps import *
from src.steps.servo_steps import *


class M02GrabFirstPomsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            # drive infront of poms
            strafe_right(20, 1.0),
            servo_shild_up(999),
            strafe_left(20, 1.0),

            parallel(
                seq([ #turn and prepear to set down the the claw
                    turn_right(90, 1.0),
                ]),
                seq([ #repears the servo to move down while moving bacwards
                    servo_pom_arm_up(),
                    servo_pom_grab_open(),
                ]),
            ),
            drive_backward(5, 1),
            servo_pom_arm_down(),

            parallel(
                # get poms and close claw
                seq([
                    frontside_line_follow_right_edge(145, 1.0),  # drives down acces ramp
                    drive_forward(40, 1.0), # TODO: do only line following; currently line follow does weird thing at the end
                ]),
                seq([
                    #close the claw a bit, so fully closing it is faster
                    servo_pom_grab_slightly_open(999),
                    #wait until we have collected all poms
                    wait_until_distance(42),
                    #wait(2.2),
                    servo_pom_grab_close(999),
                    servo_pom_arm_up(),
                ]),
            ),
        ])