"""
===========================================================
 Project:   PackingBot
 Generated: 2026-03-10 20:32:51
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *
from src.hardware.defs import Defs

def line_follow(speed = 1.0):
    return strafe_follow_line_single(
        Defs.front.left,
        speed=speed,
        side=LineSide.LEFT,
        kp=0.5,
        ki=0.3,
        kd=0.0,
    )


class M060DriveToBasketsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            background(
                seq([
                    Defs.shild.high_up(),
                ]),
            ),

            #make sure the bot straight
            turn_to_heading_right(0),

            #drive to baskets
            line_follow().until(
                on_black(Defs.rear.right) +
                after_cm(22)
            ),

            turn_left().until(after_degrees(50) | after_seconds(1.0)),
            #put the arm back up
            background(
                seq([
                    Defs.shild.save_up(),
                    Defs.pom_arm.start(90),
                ]),
            ),
            #turn back straight
            turn_to_heading_right(0, 1.0),

            line_follow().until(
                    over_line(Defs.rear.right) +
                after_cm(15)
            ),
        ])