"""
===========================================================
 Project:   PackingBot
 Generated: 2026-03-10 20:32:51
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *
from src.hardware.defs import Defs

def line_follow(speed = 1.0):
    return strafe_follow_line_single(
        Defs.front.left,
        speed=speed,
        side=LineSide.LEFT,
        kp=0.5,
        kd=0.1,
    )


class M06DriveToBasketsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            strafe_left(speed=1.0).until(on_black(Defs.front.left)),

            #get rid of fist traffic conde
            turn_left(degrees=40),
            parallel(
                turn_to_heading_right(0, 1.0),
                Defs.pom_arm.high_up(200),
            ),

            #drive until line and 15cm higher
            line_follow().until(
                on_black(Defs.rear.right) > after_cm(15),
            ),

            #get rid of second traffic conde
            parallel(
                turn_right(degrees=10),
                Defs.pom_arm.down(),
            ),
            turn_left(degrees=40),
            parallel(
                turn_to_heading_right(0, 1.0),
                Defs.pom_arm.high_up(200),
            ),

            line_follow().until(
                on_black(Defs.rear.right) > on_white(Defs.rear.right)
            ),

            #trow cubes down
            parallel(
                turn_right(degrees=10),
                Defs.pom_arm.up(),
            ),
            turn_left().until(after_seconds(0.4)),
            parallel(
                turn_to_heading_left(0),
                Defs.pom_arm.high_up(),
            ),
            wall_align_forward(1.0,0.4, 0.1, 5, 1.0),
            mark_heading_reference(),


        ])