"""
===========================================================
 Project:   PackingBot
 Generated: 2026-03-10 20:32:51
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *

class M07DriveToBasketsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            drive_forward(90, 1.0),
        ])