"""
===========================================================
 Project:   PackingBot
 Generated: 2026-03-24 17:41:44
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *

from src.hardware.defs import Defs

class M080MoveBasketsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            #drive in the middle of the baskets
            parallel(
                Defs.shild.above_pasked(),
                drive_forward(13),
            ),

            #grap basktets
            strafe_right().until(
                on_black(Defs.front.left) >
                on_white(Defs.front.left)
            ),
            Defs.shild.above_pasked(),
            strafe_right(cm=1),
            Defs.shild.grab_pasked(),

            strafe_left().until(
                on_black(Defs.front.right) >
                after_cm(12)
            ),

            drive_backward() .until(
                on_black(Defs.front.left) >
                after_cm(15)
            ),

            #let basktes go
            Defs.shild._45deg(),


        ])