"""
===========================================================
 Project:   PackingBot
 Generated: 2026-03-15 10:55:52
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *

from src.hardware.defs import Defs


class M08DropSortedPomsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            strafe_left().until(on_black(Defs.front.right)),
            strafe_left().until(on_white(Defs.front.right)),
            strafe_left(cm=2),

            #drive backwards to line
            strafe_follow_line_single(Defs.front.right, #drive to line
                                      speed=-1,
                                      side=LineSide.RIGHT,
                                      kp=0.4,
                                      kd=0.1,
                                      ).until(on_black(Defs.front.left)),

            strafe_follow_line_single(Defs.front.right, #drive further with hardcode
                                      speed=-1,
                                      side=LineSide.RIGHT,
                                      kp=0.4,
                                      kd=0.1,
                                      ).distance_cm(15),
            #drop poms
            turn_to_heading(degrees=-15),
            Defs.shild_graber.open(),
            wait_for_seconds(0.3),
            Defs.shild_graber.closed(),
            turn_to_heading(degrees=0),

            #let baskeds go
            Defs.shild.above_pasked(),
            strafe_left(cm=5),
            drive_backward(cm=15),

            #push sorted poms in half way
            strafe_right().until(on_black(Defs.front.left)),
                #put shild down
            strafe_left(cm=10),
            Defs.shild.down(),
                #push sorted poms in fully
            strafe_right().until(on_black(Defs.front.left)),
            strafe_right().until(on_white(Defs.front.left)),
            strafe_right(cm=5),
        ])