"""
===========================================================
 Project:   PackingBot
 Generated: 2026-03-15 15:38:31
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import *
from src.hardware.defs import Defs


class M08DropMachingPomsMission(Mission):
    def sequence(self) -> Sequential:
        return seq([
            #align oursfls for basket
            strafe_left().until(
                on_black(Defs.front.left) > on_white(Defs.front.left)
            ),
            drive_backward().until(on_black(Defs.rear.right)),

            #turn to basket
            turn_right(degrees=30),

            Defs.pom_arm.above_basket(),

            shake_servo(
                Defs.pom_grab,
                5,
                Defs.pom_grab.closed.value,
                Defs.pom_grab.open.value,
            ),
        ])